# Site settings
title: MonitorHARO
email: support@crankwheel.com
description: > # this means to ignore newlines until "baseurl:"
  We monitor HARO so you don’t have to. Pitch all the right journalists
  and save 7+ hours a month for just $28.
baseurl: ""
url: "http://monitorharo.com"

# Build settings
markdown: kramdown
